---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUWkb2RJdZQKq8DZZdg9yncKSBblAwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTE5MTQ0MjAwWhcNMjQxMTE3MTQ0MjAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ALvHzcn38s2yTTVi9ZvDE/b/DN0pMyQ3lHR4k808vl+m7kY8gO0sQus1PLG4oRT8
    l2UQOG2moitpLkvsCFYrcPiaVcyY0lM+R0yIOQLOOCvIVS7GuTekKmDMCBzaUmHM
    lX9Iz/GCkqEkbOYHW3k9R4gaqEscJ7CtYyJdhIgueNfJdnOsfaPO7Qe6oJ4m1u1J
    w5TKnaU/r1Mj71wA00J5BJ4sm7Ip6idY2bCSsJ2IibSZFhzO+04Q9v0PDplkFmLn
    70iTUt0sA7dnsxYgoLwu/BPxcA49VUczhJxAVUqMrr379fCHVVHLnXDY3HRONVT1
    CdggQBOPC1SjSsf2r41jbz+GBdDiKBnrZx0DLia1qjlS5on89/5SgbStCXn/8anf
    Sw7Hw/RiBPXAVJStDdD8Bz8cXuHv0TjkAg6PCUbsvNy1BMXZHizs/7dCbawwzBTr
    DYFQ6uqCV2Ezl4Ho+9OjqmbiKiHDAh2Wan04rC4fUgYrJvw3D+avbmJ+qbpzPY79
    z4j32M3BaU5+rFRNgyJlK3u7O7sn/ohdLNOPGIguY0IceTpA8HaZddXbZztyAHAk
    RZy2xbhpQZHsbBRFJaNRjmd7Y/kZv9NDm14MBZGpn4Yr6ioI7AD1lb1DhwuiUu02
    /28mOVeYe6DraUpTrRsrDLJ2xrPDUzxn2VoViaP8/f59AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSc00qd+eSf4WzV
    hDY4dYl4DC7kVzANBgkqhkiG9w0BAQ0FAAOCAgEAEcMG27cA+eyQC/0MSIklMkQT
    pT++PnHXAGnEowly9/uCX+91C5AEg4VXX/GUb2hO7RgpkdPSfmMmNLlJCQwBexYE
    LEWBdLJkFr/cpZItnlXMu20fX2yyiSXCxdhwfie8+ygkJcHnJKGQaAJ7tOpoNSS9
    kFXxdqHOJHV5FQbJVd67O8glnH+TNgi0+69+3QMM81ugV/PBBct9RkJY9jj5TicZ
    htFZEFcX7LlzSW7SrpewiM69vZ6QqmN+zMvDTpw2OzwK6vvkENma/lxT2OupVeVL
    yDo2+Qe84TfAEdr15JqR33pK89MnrKStCbKTobPcOIoR/U3wTKJNS/Jz7Xj9qLTJ
    txdzLW+8PJKMtN6Rehqoen/0BXIcWqsTIyz4pfxi3rsngWslQtGcvTQ3DzS4NjGX
    eZKFKwf8fMbLqaD3wnJx9uY7FSXDY144kQjJpvYqpFn790wI7qms9+nV42icdcQP
    +flEaM6+GHJHGDb2xgRNZ+Ho8Ju1zSgshTJYkiYZL06IWQnORCtXnQ1017KIvMjM
    HzQDuSd4ckTpH5lzVIhIjxBABTAhXliO2iEE0ab69iJOm9sXlJJiKvm/Q7ibUwES
    l96v5xrpIJ1q6p89nyd/+Jk1f6DY2U+QgPg3x7FMncJTTo91XD/+wE8Yk4gCx+6o
    /IbHuSn4ICi3KArwDro=
    -----END CERTIFICATE-----
    
